<a href="https://colab.research.google.com/github/HansonLee2015/AIoT-practice/blob/main/Python1_2025_3_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
import copy
import numpy
list1 = [[1, 2, 3], [4, 5, 6]]
# list2 = copy.copy(list1)
list2 = copy.deepcopy(list1)
# list 2 = list 1
list2[0][0] = 99

print ("list1:", list1)
print("list2:", list2)
print(numpy.array(list).shape)

list1: [[1, 2, 3], [4, 5, 6]]
list2: [[99, 2, 3], [4, 5, 6]]
()


In [ ]:
x, y, z = 1, 2, 3
x = y = z
print(x, y, z)

3 3 3


In [ ]:
numbers = [1, 2, 3]
numbers.append(4)
print(numbers) #[1, 2, 3, 4]
#append報告會用到

[1, 2, 3, 4]


In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]
a.extend(b)
print(a)

[1, 2, 3, 4, 5, 6]


In [ ]:
 l = [1, 2, 3, 4]
 index = 0, 1, 2, 3
#  l[0] = 1
#  l[0] = 2

In [ ]:
fruits = ['apple', 'banana']
fruits.insert(1, 'orange')
print(fruits) #['apple', 'orange', 'banana']

['apple', 'orange', 'banana']


In [ ]:
numbers = [1, 2, 3, 2, 4]
numbers.remove(1)
print(numbers) #[1, 3, 2, 4]
#(只刪除第一個2)

[2, 3, 2, 4]


In [ ]:
numbers = [1, 2, 3, 4]
last = numbers.pop()
print(numbers) #[1, 2, 3]
print(last) #4

[1, 2, 3]
4


In [ ]:
numbers = [10, 20, 30, 40]
print(numbers.index(30)) #2

2


count

In [ ]:
numbers = [1, 2, 3, 2, 4, 2]
print(numbers.count(2)) #3

3


In [ ]:
numbers = [5, 2, 9, 1]
numbers.sort()
print(numbers)

numbers.sort(reverse=True)
print(numbers) # [9, 5, 2, 1] (降序)

[1, 2, 5, 9]
[9, 5, 2, 1]


In [ ]:
numbers = [5, 2, 9, 1]
numbers.sort()
print(numbers)

numbers.sort(reverse=1)
print(numbers) # [9, 5, 2, 1] (降序)

[1, 2, 5, 9]
[9, 5, 2, 1]


In [ ]:
letters = ['a', 'b', 'c']
letters.reverse()
print(letters) #['c', 'b', 'a']

['c', 'b', 'a']


重要

In [ ]:
numbers = [10, 20, 30]
print(len(numbers))


3


In [ ]:
numbers = [10, 20, 30]
print(sum(numbers))

60


In [ ]:
numbers = [10, 20, 30]
print(max(numbers))
print(min(numbers))

30
10


In [ ]:
words = ['Hello', 'World']
sentences = '//'.join(words)
print(sentences)

Hello//World


這個出錯是正常的，要像下面那樣調整

In [ ]:
if cost > 2000:
  cost = cost * 0.95
  print ("折扣金額為：", cost)

NameError: name 'cost' is not defined

In [ ]:
cost = 3000
if cost > 2000:
  cost = cost * 0.75
  print(cost)

2250.0


In [ ]:
data = int(input('輸入一個整數：'))
if data > 2000:
  print (data, '大於2000')
else:
  print(data, '小於等於2000')

輸入一個整數：500
500 小於等於2000


2025.3.5

= 指定
== equal等於

In [ ]:
import pandas as pd
file_path = "test.xlsx"
df = pd.read_excel(file_path)
df2 = pd.read_excel('2020~2021_call_1.xlsx')
df2

會員編號       編號               會員姓名       Call In/Out 日期  \
0      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
1      C1031201882750         C107093  沈莉娟                2020-01-02 00:00:00   
2      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
3      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
4      C1011101244476         C102027  蘇靖雯                2020-01-02 00:00:00   
...                      ...      ...                ...                  ...   
89031  C0990100108266         C109054  陳玉卿                2021-12-30 00:00:00   
89032  C20200705140           C109054  陳雅青                2021-12-30 00:00:00   
89033  C1051201284774         C109054  蔡家穎                2021-12-30 00:00:00   
89034  C1041001336605         C104170  姜念劬                2021-12-30 00:00:00   
89035  C0990100211959         C109054  張禎修                2021-12-30 00:00:00   

           開始時間      結束時間 通話時間(秒)  通話狀態1         通話狀態2  
0      10:03:17  10:03:17       0  推薦舊產品        沒聯絡上本人  
1      10:12:57  10:14:42     105   關心聯絡          到貨確認  
2      10:38:08  10:38:08       0  推薦舊產品        沒聯絡上本人  
3      11:45:41  11:45:41       0  推薦舊產品        沒聯絡上本人  
4      14:30:59  14:31:50      51  推薦舊產品     其他(請詳填備註)  
...         ...       ...     ...    ...           ...  
89031  17:49:10  17:49:10       0   關心聯絡        沒聯絡上本人  
89032  17:53:29  17:53:29       0   關心聯絡        沒聯絡上本人  
89033  17:55:52  17:55:52       0   關心聯絡        沒聯絡上本人  
89034  17:57:32  18:24:37    1625   關心聯絡  關心寒暄(OB-下訂單)  
89035  17:58:52  17:58:52       0   關心聯絡        沒聯絡上本人  

[89036 rows x 9 columns]

In [ ]:
import pandas as pd
file_path = "test.xlsx"
df = pd.read_excel(file_path)
df2 = pd.read_excel('2020~2021_call_1.xlsx')
print(df)
print(df2)

               會員編號
0    C1031201268066
1    C0980100043223
2    C1051201373270
3    C0990100115387
4    C8101000017547
..              ...
478  C1020701180541
479  C1011101039232
480  C1030000015239
481    C20190315021
482  C1041001435728

[483 rows x 1 columns]
                        會員編號       編號               會員姓名       Call In/Out 日期  \
0      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
1      C1031201882750         C107093  沈莉娟                2020-01-02 00:00:00   
2      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
3      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
4      C1011101244476         C102027  蘇靖雯                2020-01-02 00:00:00   
...                      ...      ...                ...                  ...   
89031  C0990100108266         C109054  陳玉卿                2021-12-30 00:00:00   
89032  C20200705140           C109054  陳雅青                2021-12-30 00:00:00   
89033  

In [ ]:
import pandas as pd
file_path = "test.xlsx"
df = pd.read_excel(file_path)
print(df)

               會員編號
0    C1031201268066
1    C0980100043223
2    C1051201373270
3    C0990100115387
4    C8101000017547
..              ...
478  C1020701180541
479  C1011101039232
480  C1030000015239
481    C20190315021
482  C1041001435728

[483 rows x 1 columns]


In [ ]:
import pandas as pd
file_path = "test.xlsx"
df = pd.read_excel(file_path)
df

會員編號
0    C1031201268066
1    C0980100043223
2    C1051201373270
3    C0990100115387
4    C8101000017547
..              ...
478  C1020701180541
479  C1011101039232
480  C1030000015239
481    C20190315021
482  C1041001435728

[483 rows x 1 columns]

In [ ]:
import pandas as pd
file_path = "2020~2021_call_1.xlsx"
df = pd.read_excel(file_path)
df

會員編號       編號               會員姓名       Call In/Out 日期  \
0      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
1      C1031201882750         C107093  沈莉娟                2020-01-02 00:00:00   
2      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
3      C1030000005865         C102027  王九妹                2020-01-02 00:00:00   
4      C1011101244476         C102027  蘇靖雯                2020-01-02 00:00:00   
...                      ...      ...                ...                  ...   
89031  C0990100108266         C109054  陳玉卿                2021-12-30 00:00:00   
89032  C20200705140           C109054  陳雅青                2021-12-30 00:00:00   
89033  C1051201284774         C109054  蔡家穎                2021-12-30 00:00:00   
89034  C1041001336605         C104170  姜念劬                2021-12-30 00:00:00   
89035  C0990100211959         C109054  張禎修                2021-12-30 00:00:00   

           開始時間      結束時間 通話時間(秒)  通話狀態1         通話狀態2  
0      10:03:17  10:03:17       0  推薦舊產品        沒聯絡上本人  
1      10:12:57  10:14:42     105   關心聯絡          到貨確認  
2      10:38:08  10:38:08       0  推薦舊產品        沒聯絡上本人  
3      11:45:41  11:45:41       0  推薦舊產品        沒聯絡上本人  
4      14:30:59  14:31:50      51  推薦舊產品     其他(請詳填備註)  
...         ...       ...     ...    ...           ...  
89031  17:49:10  17:49:10       0   關心聯絡        沒聯絡上本人  
89032  17:53:29  17:53:29       0   關心聯絡        沒聯絡上本人  
89033  17:55:52  17:55:52       0   關心聯絡        沒聯絡上本人  
89034  17:57:32  18:24:37    1625   關心聯絡  關心寒暄(OB-下訂單)  
89035  17:58:52  17:58:52       0   關心聯絡        沒聯絡上本人  

[89036 rows x 9 columns]

while 條件: 條件成立時做

In [ ]:
次數, 目標 = 0, 5
while 次數 < 目標:
    print("已經練習了{}\t開始第{}次的練習".format(次數, 次數+1))
    次數 += 1
else:
    print("達成目標，共練習了{}次".format(次數))


已經練習了0	開始第1次的練習
已經練習了1	開始第2次的練習
已經練習了2	開始第3次的練習
已經練習了3	開始第4次的練習
已經練習了4	開始第5次的練習
達成目標，共練習了5次


In [ ]:
次數 = 0
目標 = int(input('輸入聯繫次數：'))
while 次數 < 目標:
  print("練習次數{}次".format(次數+1))
  次數 += 1
else:
  print("達成目標,一共聯繫了{}次".format(次數))

輸入聯繫次數：3
練習次數1次
練習次數2次
練習次數3次
達成目標,一共聯繫了3次


In [ ]:
次數 = 0
目標 = int(input('輸入練習次數：'))
while 次數 < 目標:
    print("練習第{}次".format(次數+1))
    次數 += 1
else:
    print("達成目標，共練習了{}次".format(次數))


輸入練習次數：3
練習第1次
練習第2次
練習第3次
達成目標，共練習了3次


In [ ]:
data = ['Mon.','Tue.','Wed.','Thr.','Fri.']
for c in data:
  print(c, end='')

Mon.Tue.Wed.Thr.Fri.

In [ ]:
data = ['Mon.','Tue.','Wed.','Thr.','Fri.']
for c in data:
  print(c, end='')
else:
  print()
print('=================')

Mon.Tue.Wed.Thr.Fri.


In [ ]:
seq = range(5)
seq = range(0, 5)
seq = range(1, 10, 2)
print(seq)
for c in seq:
  print(c, end='.')

range(1, 10, 2)
1.3.5.7.9.

In [ ]:
L = [1,2,3,4,5]
for c in L:
  print (c)

1
2
3
4
5


In [ ]:
seq = range(100)
print(seq)
for c in seq:
  print (c, end=',')

range(0, 100)
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,

In [ ]:
n = int(input('輸入整數N：'))
for i in range(1,n):
  print(i, end=',')
else:
  print(i+1)

輸入整數N：6
1,2,3,4,5,6


In [ ]:
for 次數:
L = [1,2,3,4,5,6]
for c in range(5):
  print(c)

SyntaxError: invalid syntax (<ipython-input-35-8d0c6dd34a16>, line 1)

In [ ]:
for 次數 in range(5):  # 確保是半形冒號
    L = [1, 2, 3, 4, 5, 6]
for c in range(5):  # 確保是半形冒號
        print(c)

0
1
2
3
4


In [ ]:
total = 0
for i in range(1, 101): #從1到100
  total += i
print("1到100的總和",total)

1到100的總和 5050


In [ ]:
total = 0
for i in range(1, 101): #從1到100
  total = total + i
print("1到100的總和",total)

1到100的總和 5050


range(x, y, z)
x:起始
y：終點-1
z：公差

In [ ]:
for 次數 in range(5):  # 確保是半形冒號
    L = [1, 2, 3, 4, 5, 6]

continue: 要跳過回圈
break：不管發生什麼事情都結束這個回圈

In [ ]:
l = [0, 0, 1, 0, 0]
for i in l:
  if i == l:
    #break
    continue
  print(i)
  #print('sasdasadfd')

0
0
1
0
0


In [ ]:
l = [0, 0, 1, 0, 0]
for i in l:
  if i == l:
    break
    #continue
  print(i)
  #print('sasdasadfd')

0
0
1
0
0


In [ ]:
def funtion_name(parameters):
  statements
  return values

In [ ]:
def f():
  print("Hello,Python!")

In [ ]:
f()

Hello,Python!


In [ ]:
import random
def 運動():
  運動時間 = random.randint(30,120)
  print("開始運動...", 運動時間,"分鐘...完成運動")

In [ ]:
for i in range(3):
  運動()

開始運動... 56 分鐘...完成運動
開始運動... 110 分鐘...完成運動
開始運動... 80 分鐘...完成運動


n是參數, 把參數傳遞進去

In [ ]:
def ABC(n):
  print(n)
ABC(7)
ABC(3)

7
3


In [ ]:
def ABC(n):
  n = 10
  print(n)
  ABC()

In [ ]:
def ABC(n,m,k,l)
ABC()

SyntaxError: expected ':' (<ipython-input-97-d273ee240dd7>, line 1)

2025.3.12

考試會考！

In [ ]:
import math

def calculate_distance (x1, y1, x2, y2):
  distance = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
  return distance


x1, y1 = map(float, input("請輸入第一點(x1, y1)：").split())
x2, y2 = map(float, input("請輸入第二點(x2, y2)：").split())

distance = calculate_distance(x1, y1, x2, y2)
print(f"兩點({x1}, {y1}) 與 ({x2}, {y2}) 之間的距離為：{distance:.2f}")

請輸入第一點(x1, y1)：2 4
請輸入第二點(x2, y2)：3 4
兩點(2.0, 4.0) 與 (3.0, 4.0) 之間的距離為：1.00


In [ ]:
a = False
if not a:
  a = 'b'
else:
  a = 'a'
print(a)

b


Attribute 不會跑
Method（Function） 會跑

In [ ]:
class Car:
  def _init_(self, brand, model, year):
    """初始化車輛屬性"""
    self.brand = brand
    self.model = model
    self.year = year
    self.is_running = False #初始階段為未啟動

  def star(self):
    """啟動車輛"""
    if not self.is_running:
      self.is_running = True
      print(f"{self.brand} {self.model} 已啟動！")
    else:
      print(f"{self.brand} {self.model} 已經在運行中！")

  def display_info(self):
    """停止車輛"""
    if not self.is_running:
      self.is_running = True
      print(f"{self.brand} {self.model} 已停止！")
    else:
      print(f"{self.brand} {self.model} 已停止運行中！")

  def display_info(self):
        """顯示車輛資訊"""
        return f"{self.year} {self.model} {self.brand}"

# 創建 Car 類別的實例
my_car = Car("Toyota", "Corolla", 2022)
my_car2 = Car("Tesla", "Model 3", 2023)

#創建 Car類別的實例
print(my_car.display_info())
print(my_car2.display_info())

my_car.start()
my_car.start()

TypeError: Car() takes no arguments

In [ ]:
class Car:
    def __init__(self, brand, model, year):
        """初始化車輛屬性"""
        self.brand = brand
        self.model = model
        self.year = year
        self.is_running = False  # 初始階段為未啟動

    def start(self):
        """啟動車輛"""
        if not self.is_running:
            self.is_running = True
            print(f"{self.brand} {self.model} 已啟動！")
        else:
            print(f"{self.brand} {self.model} 已經在運行中！")

    def stop(self):
        """停止車輛"""
        if self.is_running:
            self.is_running = False
            print(f"{self.brand} {self.model} 已停止！")
        else:
            print(f"{self.brand} {self.model} 已經是停止狀態！")

    def display_info(self):
        """顯示車輛資訊"""
        return f"{self.year} {self.model} {self.brand}"

# 創建 Car 類別的實例
my_car = Car("Toyota", "Corolla", 2022)
my_car2 = Car("Tesla", "Model 3", 2023)

# 顯示車輛資訊
print(my_car.display_info())
print(my_car2.display_info())

# 嘗試啟動與停止車輛
my_car.start()
my_car.start()  # 再次啟動應該顯示已經在運行中
my_car.stop()
my_car.stop()  # 再次停止應該顯示已經是停止狀態


2022 Corolla Toyota
2023 Model 3 Tesla
Toyota Corolla 已啟動！
Toyota Corolla 已經在運行中！
Toyota Corolla 已停止！
Toyota Corolla 已經是停止狀態！


In [ ]:
import numpy as np

#建立 numpy陳列
a = np.array({1, 2, 3, 4, 5})
print(a)

b = np.array([[1, 2, 3] , [4, 5, 6]])
print(b)

{1, 2, 3, 4, 5}
[[1 2 3]
 [4 5 6]]


In [ ]:

#創建全為0的陣列
zeros = np.zeros((3, 3))
print(zeros)

#創建全為1的陣列
ones = np.ones((3,3))
print(ones)

empty = np.empty((2,2))
print(empty)

#創建隨機數組
random_array = np.random.random((3,3)) #0～1之間的隨機數
print(random_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4.06506873e-316 0.00000000e+000]
 [1.14490784e+243 6.01347002e-154]]
[[0.85852637 0.77881366 0.20190638]
 [0.0884485  0.40310729 0.3218324 ]
 [0.77841607 0.27544252 0.40213321]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#矩陣相乘
C = np.dot(A, B)
print(C)

#計算機轉置矩陣
print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#取出第一列
print(arr[:, 0]) #[1, 4, 7]

#取出第二行
print(arr[1, :]) #[4, 5, 6]

#取出特定區域
print(arr[:2, 1:]) #[[2,3], [5, 6]]


[1 4 7]
[4 5 6]
[[2 3]
 [5 6]]


In [ ]:
data = np.array([10, 3, 8, 6, 2])

#排序
sorted_data = np.sort(data)
print(sorted_data) #[2 3 6 8 10]

#篩選大於5的值
filtered_data = data[data> 5]
print(filtered_data) #[10 8 6]
print(data> 5)
print(sorted_data> 5)

[ 2  3  6  8 10]
[10  8  6]
[ True False  True  True False]
[False False  True  True  True]


In [ ]:
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 4, 4, 5])

unique_values = np.unique(arr)
print(unique_values)
print(arr)

[1 2 3 4 5]
[1 2 2 3 3 4 4 5]


1有幾個，2有幾個...

In [ ]:
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)
print(counts)

[1 2 3 4 5]
[1 2 2 2 1]


In [ ]:
import pandas as pd

#建立字典並轉為DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'San Francisco', 'Los Angeles']
}

df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


取欄位取條件

第一次 df["Age"] > 28：
這是條件，會變成一個 True/False 的布林陣列。
第二次 df[...]：
這裡 df 使用剛才的布林陣列來篩選，只留下 True 的行。

In [ ]:
#取得特定欄位
print(df["Name"])

#篩選條件 (年齡大於 28)
filtered_df = df[df['Age'] > 28] #有兩個df，程式是從裡面看到外面
print(filtered_df)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [ ]:
#新增信欄位
df['Salary'] = [50000, 60000, 70000]
print(df)

# # 修改某些數據
# df.loc[1, 'Salary'] = 65000
# print(df)

      Name  Age           City  Salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000


In [ ]:
#基本統計
print(df.describe())

#計算平均年齡
print(df["Age"].mean())

#計算不同程式人數
print(df["City"].value_counts())

        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0
30.0
City
New York         1
San Francisco    1
Los Angeles      1
Name: count, dtype: int64
